spring:
  docker:
    compose:
      file: docker-compose.yml
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/offers
  banner:
    location: logo.txt


joboffers:
  scheduler:
    fetchOccurrence: PT3H
  http:
    client:
      config:
        uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
        port: 5057
        service: /offers
        connectTimeout: 1000
        readTimeout: 1000

scheduling:
  enabled: true


